# Generated by Django 4.0.1 on 2022-01-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='media')),
                ('telefono', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='media')),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('estado', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
