# Generated by Django 3.2.6 on 2021-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210828_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
