# Generated by Django 3.2.6 on 2021-08-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_tipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
